[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = {  version = "0.51.0", features = ["csv"] }
reqwest = "0.12.23"
scraper = "0.24.0"
zip = "5.1.1"
anyhow = "1.0.100"
